[package]
name = "matasano_cryptopals_challenges"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.3"
base64 = "0.21.3"
hex = "0.4.3"
hexxdump = "1.0.1"
indexmap = "2.0.0"
openssl = "0.10.57"
rand = "0.8.5"
